#!/bin/tcsh -f
echo "created by Rasheed"
echo "           "
echo "**       **"                     
echo " **     ** "
echo "  **   **  "
echo "   ** **   "
echo "    ***    "

set my_work_dir = 'pwd'

#-------------------------------------------------------------#
#-------------Tool Initialization-----------------------------#
#-------------------------------------------------------------#


if ($#argv != 1) then
	echo "Info: Please provide the csv file"
	exit 1
endif

if (! -f $argv[1] || $argv[1] == "-help") then
	if ($argv[1] != "-help") then
		echo "Error: cannot find csv file $argv[1].Exiting..."
		exit 1
	else
		echo "USAGE: ./rasheed\<csv file\>" 
    echo "       where \<csv file\>consists of 2 columns, below keyboard being in 1st column is being case sensitive.Please request VSD team for sample csv file"
		echo "       \<design name\> is the name of the top level module"
		echo "       \<output directory\> is the name of the output directory where you want to dump synthesis script, synthesized netlist and timing reports"  
		echo "       \<netlist directory\> is the name of directory where all RTL netlist are present"
		echo "       \<Early library path\> is the file path of early cell library to be used for STA"
		echo "       \<Late library path\> is the file path of the late cell library to be used for STA"
		echo "       \<Constratints file\> is the csv file path of constraints to be used for STA"
		echo
		exit 1
	endif
else
		tclsh rasheed.tcl $argv[1]
endif
